# Generated by Django 5.2.4 on 2025-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_program_budget_to_dollars'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('FULL', 'Повна синхронізація'), ('INCREMENTAL', 'Інкрементальна синхронізація'), ('PARTIAL', 'Часткова синхронізація')], default='FULL', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_programs', models.IntegerField(default=0)),
                ('synced_programs', models.IntegerField(default=0)),
                ('updated_programs', models.IntegerField(default=0)),
                ('deleted_programs', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('RUNNING', 'Виконується'), ('COMPLETED', 'Завершено'), ('FAILED', 'Помилка'), ('CANCELLED', 'Скасовано')], default='RUNNING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='YelpProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('program_type', models.CharField(db_index=True, max_length=20)),
                ('program_status', models.CharField(db_index=True, max_length=20)),
                ('program_pause_status', models.CharField(default='NOT_PAUSED', max_length=20)),
                ('yelp_business_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('partner_business_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active_features', models.JSONField(blank=True, default=list)),
                ('available_features', models.JSONField(blank=True, default=list)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_autobid', models.BooleanField(blank=True, null=True)),
                ('max_bid', models.BigIntegerField(blank=True, null=True)),
                ('fee_period', models.CharField(blank=True, max_length=50, null=True)),
                ('billed_impressions', models.BigIntegerField(blank=True, null=True)),
                ('billed_clicks', models.BigIntegerField(blank=True, null=True)),
                ('ad_cost', models.BigIntegerField(blank=True, null=True)),
                ('future_budget_changes', models.JSONField(blank=True, default=list)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['program_id'], name='ads_yelppro_program_ca8f18_idx'), models.Index(fields=['program_type', 'program_status'], name='ads_yelppro_program_bff18f_idx'), models.Index(fields=['yelp_business_id'], name='ads_yelppro_yelp_bu_36efd2_idx'), models.Index(fields=['start_date', 'end_date'], name='ads_yelppro_start_d_7b22be_idx'), models.Index(fields=['last_synced'], name='ads_yelppro_last_sy_6e7332_idx'), models.Index(fields=['is_deleted'], name='ads_yelppro_is_dele_cc50f7_idx')],
            },
        ),
    ]
