# Generated by Django 5.2.5 on 2025-10-09 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_customsuggestedkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('biz_photo_id', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', models.TextField(blank=True)),
                ('is_before_photo', models.BooleanField(default=False)),
                ('is_cover_photo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('program_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('call_to_action', models.CharField(choices=[('WEBSITE', 'Website'), ('CALL', 'Call'), ('BOOK_APPOINTMENT', 'Book Appointment'), ('GET_QUOTE', 'Get Quote'), ('LEARN_MORE', 'Learn More')], max_length=50)),
                ('service_offerings', models.JSONField(blank=True, default=list)),
                ('cost', models.CharField(blank=True, choices=[('UNDER_100', 'Under $100'), ('100_500', '$100 - $500'), ('500_1000', '$500 - $1,000'), ('1000_5000', '$1,000 - $5,000'), ('5000_PLUS', '$5,000+')], max_length=20, null=True)),
                ('duration', models.CharField(blank=True, choices=[('UNDER_1_WEEK', 'Under 1 week'), ('1_2_WEEKS', '1-2 weeks'), ('2_4_WEEKS', '2-4 weeks'), ('1_3_MONTHS', '1-3 months'), ('3_PLUS_MONTHS', '3+ months')], max_length=20, null=True)),
                ('completion_year', models.IntegerField(blank=True, null=True)),
                ('completion_month', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(db_index=True, max_length=100)),
                ('feature_type', models.CharField(choices=[('LINK_TRACKING', 'Link Tracking'), ('NEGATIVE_KEYWORD_TARGETING', 'Negative Keyword Targeting'), ('STRICT_CATEGORY_TARGETING', 'Strict Category Targeting'), ('AD_SCHEDULING', 'Ad Scheduling'), ('CUSTOM_LOCATION_TARGETING', 'Custom Location Targeting'), ('AD_GOAL', 'Ad Goal'), ('CALL_TRACKING', 'Call Tracking'), ('BUSINESS_HIGHLIGHTS', 'Business Highlights'), ('VERIFIED_LICENSE', 'Verified License'), ('CUSTOM_RADIUS_TARGETING', 'Custom Radius Targeting'), ('CUSTOM_AD_TEXT', 'Custom Ad Text'), ('CUSTOM_AD_PHOTO', 'Custom Ad Photo'), ('BUSINESS_LOGO', 'Business Logo'), ('YELP_PORTFOLIO', 'Yelp Portfolio')], max_length=50)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='customsuggestedkeyword',
            new_name='ads_customs_program_d4eb92_idx',
            old_name='ads_customsu_program_idx',
        ),
        migrations.RenameIndex(
            model_name='customsuggestedkeyword',
            new_name='ads_customs_keyword_f9d65d_idx',
            old_name='ads_customsu_keyword_idx',
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['program_id'], name='ads_portfol_program_f52d96_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['project_id'], name='ads_portfol_project_a039ee_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['published'], name='ads_portfol_publish_8ea814_idx'),
        ),
        migrations.AddField(
            model_name='portfoliophoto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ads.portfolioproject'),
        ),
        migrations.AddIndex(
            model_name='programfeature',
            index=models.Index(fields=['program_id'], name='ads_program_program_23bd80_idx'),
        ),
        migrations.AddIndex(
            model_name='programfeature',
            index=models.Index(fields=['feature_type'], name='ads_program_feature_4adc01_idx'),
        ),
        migrations.AddIndex(
            model_name='programfeature',
            index=models.Index(fields=['is_active'], name='ads_program_is_acti_c877f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programfeature',
            unique_together={('program_id', 'feature_type')},
        ),
        migrations.AddIndex(
            model_name='portfoliophoto',
            index=models.Index(fields=['project'], name='ads_portfol_project_cf416a_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliophoto',
            index=models.Index(fields=['is_cover_photo'], name='ads_portfol_is_cove_85aec3_idx'),
        ),
    ]
