# Generated by Django 5.2.5 on 2025-10-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_portfoliophoto_portfolioproject_programfeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('logger_name', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Request duration in seconds', null=True)),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'level'], name='ads_logentr_timesta_7a4925_idx'), models.Index(fields=['level', '-timestamp'], name='ads_logentr_level_42ea5f_idx')],
            },
        ),
    ]
