# Generated by Django 5.2.5 on 2025-10-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('program_id', models.CharField(db_index=True, max_length=100)),
                ('yelp_business_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'yelp_business_id'], name='ads_program_usernam_588bdf_idx'), models.Index(fields=['username', 'program_id'], name='ads_program_usernam_0ff760_idx')],
                'unique_together': {('username', 'program_id')},
            },
        ),
    ]
