# Generated by Django 5.2.5 on 2025-10-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_programregistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='programregistry',
            name='program_name',
            field=models.CharField(blank=True, help_text='Program type: CPC, BP, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Program status: CURRENT, PAST, FUTURE, PAUSED', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='programregistry',
            index=models.Index(fields=['username', 'status'], name='ads_program_usernam_f0dfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistry',
            index=models.Index(fields=['username', 'yelp_business_id', 'status'], name='ads_program_usernam_5babcd_idx'),
        ),
    ]
