# Generated by Django 5.2.5 on 2025-10-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_programregistry_program_name_programregistry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programregistry',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Custom name for the program (user-editable)', max_length=255, null=True),
        ),
    ]
