# Generated by Django 5.2.5 on 2025-10-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_programregistry_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='programregistry',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business name from Yelp Fusion API', max_length=255, null=True),
        ),
    ]
