# Generated by Django 5.2.5 on 2025-10-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_programregistry_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='programregistry',
            name='active_features',
            field=models.JSONField(blank=True, default=list, help_text='List of active features', null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='ad_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total ad cost in dollars', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='available_features',
            field=models.JSONField(blank=True, default=list, help_text='List of available features', null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='billed_clicks',
            field=models.IntegerField(blank=True, default=0, help_text='Total billed clicks', null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='billed_impressions',
            field=models.IntegerField(blank=True, default=0, help_text='Total billed impressions', null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Program budget in dollars', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='businesses',
            field=models.JSONField(blank=True, default=list, help_text='List of businesses associated with this program', null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='currency',
            field=models.CharField(blank=True, default='USD', help_text='Currency code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='end_date',
            field=models.DateField(blank=True, help_text='Program end date', null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='fee_period',
            field=models.CharField(blank=True, help_text='Fee period: Calendar Month, Not Billed, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='is_autobid',
            field=models.BooleanField(blank=True, help_text='Whether autobidding is enabled', null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='max_bid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum bid amount in dollars', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='partner_business_id',
            field=models.CharField(blank=True, help_text='Partner business ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='program_pause_status',
            field=models.CharField(blank=True, help_text='Pause status: NOT_PAUSED, PAUSED, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='program_status',
            field=models.CharField(blank=True, help_text='Program status from API: ACTIVE, INACTIVE, etc.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='programregistry',
            name='start_date',
            field=models.DateField(blank=True, help_text='Program start date', null=True),
        ),
    ]
