# Generated by Django 5.2.5 on 2025-10-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_programregistry_active_features_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='programregistry',
            index=models.Index(fields=['username', 'program_name'], name='ads_program_usernam_8c6a48_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistry',
            index=models.Index(fields=['username', 'status', 'program_name'], name='ads_program_usernam_0271cc_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistry',
            index=models.Index(fields=['username', 'yelp_business_id', 'program_name'], name='ads_program_usernam_d4a89d_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistry',
            index=models.Index(fields=['username', 'yelp_business_id', 'status', 'program_name'], name='ads_program_usernam_fd4d11_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistry',
            index=models.Index(fields=['yelp_business_id', 'business_name'], name='ads_program_yelp_bu_1120e3_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistry',
            index=models.Index(fields=['username', 'program_status'], name='ads_program_usernam_f8f4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistry',
            index=models.Index(fields=['username', 'start_date'], name='ads_program_usernam_b53d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistry',
            index=models.Index(fields=['username', 'updated_at'], name='ads_program_usernam_1c00dd_idx'),
        ),
    ]
