# Generated by Django 5.2.5 on 2025-10-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_programregistry_ads_program_usernam_8c6a48_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programregistry',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business name from Yelp Fusion API (deprecated, use business FK)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yelp_business_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('cached_at', models.DateTimeField(auto_now=True, help_text='Last updated from API')),
                ('fetch_failed', models.BooleanField(default=False, help_text='API fetch failed')),
            ],
            options={
                'db_table': 'ads_business',
                'indexes': [models.Index(fields=['yelp_business_id', 'name'], name='ads_busines_yelp_bu_13b71a_idx')],
            },
        ),
        migrations.AddField(
            model_name='programregistry',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Link to business details', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='ads.business'),
        ),
    ]
