# Generated by Django 5.2.5 on 2025-10-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_alter_programregistry_business_name_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
