# Generated by Django 5.2.5 on 2025-10-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_alter_business_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='programregistry',
            index=models.Index(fields=['username', 'status', '-start_date'], name='ads_program_usernam_cb2094_idx'),
        ),
    ]
