# Generated by Django 5.2.7 on 2025-10-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_scheduledpause'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(blank=True, db_index=True, help_text='Program ID once created', max_length=100, null=True)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('scheduled_datetime', models.DateTimeField(db_index=True, help_text='Date and time when program should be created and launched')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, help_text='When the program was actually created', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if creation failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_params', models.JSONField(help_text='Program parameters (business_id, program_name, etc.)')),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.RenameIndex(
            model_name='scheduledpause',
            new_name='ads_schedul_program_83aecf_idx',
            old_name='ads_schedul_program_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledpause',
            new_name='ads_schedul_schedul_db9260_idx',
            old_name='ads_schedul_schedule_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledpause',
            new_name='ads_schedul_usernam_55bf81_idx',
            old_name='ads_schedul_usernam_status_idx',
        ),
        migrations.AddIndex(
            model_name='scheduledprogram',
            index=models.Index(fields=['program_id', 'status'], name='ads_schedul_program_00f8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledprogram',
            index=models.Index(fields=['scheduled_datetime', 'status'], name='ads_schedul_schedul_0d63c2_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledprogram',
            index=models.Index(fields=['username', 'status'], name='ads_schedul_usernam_49c328_idx'),
        ),
    ]
