# Generated by Django 5.2.7 on 2025-10-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_scheduledprogram_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledProgram',
        ),
    ]
