# Generated by Django 5.2.7 on 2025-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_delete_scheduledprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledBudgetUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('new_budget', models.DecimalField(decimal_places=2, help_text='New budget amount in cents', max_digits=12)),
                ('scheduled_datetime', models.DateTimeField(db_index=True, help_text='Date and time when budget should be updated')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, help_text='When the update was actually executed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_datetime'],
                'indexes': [models.Index(fields=['program_id', 'status'], name='ads_schedul_program_8db06d_idx'), models.Index(fields=['scheduled_datetime', 'status'], name='ads_schedul_schedul_148620_idx'), models.Index(fields=['username', 'status'], name='ads_schedul_usernam_2251aa_idx')],
            },
        ),
    ]
