# Generated by Django 5.2.7 on 2025-10-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_scheduledbudgetupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledbudgetupdate',
            name='is_autobid',
            field=models.BooleanField(blank=True, help_text='Automatic bidding enabled', null=True),
        ),
        migrations.AddField(
            model_name='scheduledbudgetupdate',
            name='max_bid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max bid in cents (for manual bidding)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='scheduledbudgetupdate',
            name='pacing_method',
            field=models.CharField(blank=True, help_text='Pacing method: paced or unpaced', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledbudgetupdate',
            name='new_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='New budget amount in cents', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledbudgetupdate',
            name='scheduled_datetime',
            field=models.DateTimeField(db_index=True, help_text='Date and time when update should be applied'),
        ),
    ]
